// <auto-generated />
namespace SRIS.Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addusid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addusid));
        
        string IMigrationMetadata.Id
        {
            get { return "201804230243289_addusid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
